micronaut:
  server:
    port: 8081
rabbitmq:
  uri: ${RABBITMQ_URL}
mongo:
  database: test
ds:
  url: jdbc:mysql://localhost:3306/whatishappen?useTimezone=true&serverTimezone=UTC
newsapi:
  url: https://newsapi.org/v2/top-headlines?country=br&apiKey=${NEWSAPI_KEY}
vault:
  path: ${VAULT_PATH:core/datasource}